# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0002_auto_20171217_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=20)),
                ('psw_str', models.CharField(max_length=20)),
            ],
        ),
    ]
