# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0004_user_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='auth',
            new_name='auth_var',
        ),
    ]
