# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0005_auto_20171217_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_var',
        ),
    ]
