# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0007_user_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
            ],
        ),
    ]
