# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0009_auto_20171224_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='img_src',
            field=models.ImageField(default='../../static/img/dog.png', upload_to='../../static/img/'),
        ),
    ]
