# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0010_auto_20171225_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='img_src',
        ),
        migrations.AddField(
            model_name='marker',
            name='document',
            field=models.FileField(default='documents/', upload_to='documents/'),
        ),
    ]
