# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0011_auto_20171225_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='document',
        ),
        migrations.AddField(
            model_name='marker',
            name='img_src',
            field=models.CharField(default='../../media/dog.png', max_length=400),
        ),
    ]
