# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0012_auto_20171225_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='psw',
            field=models.CharField(default='0000', max_length=15),
        ),
    ]
