# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0013_marker_psw'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('dog_name', models.CharField(default='unknown', max_length=40)),
                ('img_src', models.CharField(default='../../media/dog.png', max_length=400)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('psw', models.CharField(default='0000', max_length=15)),
            ],
        ),
    ]
