# Generated by Django 2.0 on 2018-01-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0015_shelter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('temperament', models.CharField(max_length=500)),
                ('apartment_friendliness', models.IntegerField(max_length=5)),
                ('child_friendliness', models.IntegerField(max_length=5)),
                ('grooming', models.IntegerField(max_length=5)),
            ],
        ),
    ]
