# Generated by Django 2.0.1 on 2018-01-11 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0021_auto_20180107_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='takemarker',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
