# Generated by Django 2.0.1 on 2018-01-11 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0022_auto_20180111_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='losted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='takemarker',
            name='losted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
