# Generated by Django 2.0.1 on 2018-01-12 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0024_auto_20180111_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('dog_name', models.CharField(default='unknown', max_length=40)),
                ('img_src', models.CharField(default='../../media/dog.png', max_length=400)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('losted_at', models.DateField(default=django.utils.timezone.now)),
                ('feature', models.CharField(default='', max_length=1000)),
                ('phone', models.CharField(default='000-0000-000', max_length=20)),
                ('reward', models.CharField(default='0000', max_length=20)),
                ('completed_at', models.DateField(default=django.utils.timezone.now)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('psw', models.CharField(default='0000', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='marker',
            name='phone',
            field=models.CharField(default='000-0000-000', max_length=20),
        ),
        migrations.AddField(
            model_name='marker',
            name='reward',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.AddField(
            model_name='takemarker',
            name='phone',
            field=models.CharField(default='000-0000-000', max_length=20),
        ),
        migrations.AddField(
            model_name='takemarker',
            name='reward',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='marker',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='marker',
            name='losted_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='takemarker',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='takemarker',
            name='losted_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
