# Generated by Django 2.0.1 on 2018-01-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0027_breed_result_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
