# Generated by Django 2.0.1 on 2018-01-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0030_auto_20180124_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='cnt',
            new_name='lost_cnt',
        ),
        migrations.AddField(
            model_name='area',
            name='take_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
