# Generated by Django 2.0 on 2018-01-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0016_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='apartment_friendliness',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='child_friendliness',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='grooming',
        ),
        migrations.AddField(
            model_name='breed',
            name='face_type',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='breed',
            name='temperament',
            field=models.CharField(default='unknown', max_length=500),
        ),
    ]
