# Generated by Django 2.0 on 2018-01-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0017_auto_20180105_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='apartment_friendliness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='breed',
            name='child_friendliness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='breed',
            name='grooming',
            field=models.IntegerField(default=0),
        ),
    ]
