# Generated by Django 2.0 on 2018-01-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0018_auto_20180105_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='fur',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
