# Generated by Django 2.0 on 2018-01-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0019_breed_fur'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='temp_group',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
