# Generated by Django 2.0.1 on 2018-01-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0023_auto_20180111_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='feature',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='takemarker',
            name='feature',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
