# Generated by Django 2.0 on 2018-01-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0025_auto_20180112_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='k_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
